# Generated by Django 4.2.1 on 2023-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="sub_task",
            field=models.ManyToManyField(to="tasks.subtask"),
        ),
    ]
