# Generated by Django 4.2.1 on 2023-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_subtask_alter_task_sub_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="sub_task",
            new_name="sub_tasks",
        ),
    ]
