# Generated by Django 4.2.1 on 2023-08-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_sub_task_task_sub_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="columns",
        ),
        migrations.AddField(
            model_name="column",
            name="board",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tasks.board"
            ),
        ),
    ]
